"use client";

import { useState } from "react";
import { botswanaPlaces, constructionTradeTypes, quoteStages } from "@bokang/domain-data";

type Lead={id:string;client:string;trade:string;location:string;value:string;stage:string};
const starter:Lead[]=[{id:"BQ-401",client:"Metsi Retail",trade:"Renovation",location:"Gaborone",value:"P85,000",stage:"Estimating"},{id:"BQ-402",client:"Kago Properties",trade:"Electrical",location:"Tlokweng",value:"P24,500",stage:"Quote sent"}];
export function BuildQuoteShowcase(){
 const [items,setItems]=useState(starter); const [client,setClient]=useState(""); const [trade,setTrade]=useState<(typeof constructionTradeTypes)[number]>("General building"); const [location,setLocation]=useState<(typeof botswanaPlaces)[number]>("Gaborone"); const [view,setView]=useState<"leads"|"new"|"projects"|"analytics">("leads");
 function add(){if(!client.trim())return;setItems(c=>[{id:`BQ-${400+c.length+1}`,client:client.trim(),trade,location,value:"TBD",stage:"New lead"},...c]);setClient("");setView("leads");}
 return <section style={{marginTop:28,display:"grid",gap:18}}>
  <div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{([["leads","Quotes & leads"],["new","New quote"],["projects","Projects"],["analytics","Analytics"]] as const).map(([k,l])=><button key={k} onClick={()=>setView(k)} style={{border:"1px solid #d0d5dd",background:view===k?"#101827":"#fff",color:view===k?"#fff":"#344054",borderRadius:999,padding:"9px 14px",fontWeight:800}}>{l}</button>)}</div>
  {view==="leads"&&<div style={{background:"#fff",border:"1px solid #e5e7eb",borderRadius:22,overflow:"hidden"}}>{items.map(x=><div key={x.id} style={{padding:16,borderBottom:"1px solid #f0f2f5",display:"grid",gap:6}}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><strong>{x.client}</strong><div style={{fontSize:12,color:"#667085"}}>{x.trade} · {x.location} · {x.value}</div></div><select value={x.stage} onChange={e=>setItems(c=>c.map(y=>y.id===x.id?{...y,stage:e.target.value}:y))} style={{border:"1px solid #d0d5dd",borderRadius:12,padding:"8px 10px"}}>{quoteStages.map(s=><option key={s}>{s}</option>)}</select></div></div>)}</div>}
  {view==="new"&&<div style={{background:"#fff",border:"1px solid #e5e7eb",borderRadius:22,padding:20}}><h2 style={{marginTop:0}}>Capture quote opportunity</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:14}}><label style={{display:"grid",gap:6,fontSize:12,fontWeight:800}}>Client<input value={client} onChange={e=>setClient(e.target.value)} style={{border:"1px solid #d0d5dd",borderRadius:12,padding:11}}/></label><label style={{display:"grid",gap:6,fontSize:12,fontWeight:800}}>Trade<select value={trade} onChange={e=>setTrade(e.target.value as typeof trade)} style={{border:"1px solid #d0d5dd",borderRadius:12,padding:11}}>{constructionTradeTypes.map(x=><option key={x}>{x}</option>)}</select></label><label style={{display:"grid",gap:6,fontSize:12,fontWeight:800}}>Location<select value={location} onChange={e=>setLocation(e.target.value as typeof location)} style={{border:"1px solid #d0d5dd",borderRadius:12,padding:11}}>{botswanaPlaces.map(x=><option key={x}>{x}</option>)}</select></label></div><button onClick={add} style={{marginTop:16,border:0,borderRadius:12,padding:"12px 18px",background:"#2563eb",color:"#fff",fontWeight:850}}>Create quote lead</button></div>}
  {view==="projects"&&<div style={{background:"#fff",border:"1px solid #e5e7eb",borderRadius:22,padding:20}}><h2 style={{marginTop:0}}>Active projects</h2>{[["Office fit-out","68%","Next: ceiling & lighting"],["Residential extension","42%","Next: blockwork inspection"]].map(([n,p,next])=><div key={n} style={{padding:"13px 0",borderBottom:"1px solid #f0f2f5"}}><div style={{display:"flex",justifyContent:"space-between"}}><strong>{n}</strong><span>{p}</span></div><div style={{fontSize:12,color:"#667085",marginTop:4}}>{next}</div></div>)}</div>}
  {view==="analytics"&&<div style={{background:"#fff",border:"1px solid #e5e7eb",borderRadius:22,padding:20}}><h2 style={{marginTop:0}}>Commercial snapshot</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(160px,1fr))",gap:12}}>{[["Quote win rate","41%"],["Pipeline","P412k"],["Active projects","5"],["Site visits","7"]].map(([l,v])=><div key={l} style={{border:"1px solid #e5e7eb",borderRadius:16,padding:16}}><div style={{fontSize:12,color:"#667085"}}>{l}</div><strong style={{fontSize:24}}>{v}</strong></div>)}</div></div>}
 </section>;
}
