"use client";

import { useState } from "react";
import { usePersistentState } from "@bokang/persistence";
import { botswanaPlaces, tourismExperienceTypes } from "@bokang/domain-data";

type Experience={id:string;name:string;type:string;location:string;price:string;saved:boolean};
const starter:Experience[]=[{id:"BW-01",name:"Okavango Delta Escape",type:"Safari",location:"Maun",price:"From P4,800",saved:true},{id:"BW-02",name:"Chobe River Day",type:"Safari",location:"Kasane",price:"From P1,950",saved:false},{id:"BW-03",name:"Gaborone Culture Trail",type:"Cultural experience",location:"Gaborone",price:"From P650",saved:false}];
export function ExploreBWShowcase(){
 const [items,setItems]=usePersistentState("bokang-studio.explore-bw.experiences.v1", starter); const [view,setView]=useState<"explore"|"itinerary"|"booking"|"operator">("explore"); const [destination,setDestination]=useState<(typeof botswanaPlaces)[number]>("Maun"); const [kind,setKind]=useState<(typeof tourismExperienceTypes)[number]>("Safari");
 return <section style={{marginTop:28,display:"grid",gap:18}}>
  <div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{([["explore","Explore"],["itinerary","Itinerary"],["booking","Booking"],["operator","Operator dashboard"]] as const).map(([k,l])=><button key={k} onClick={()=>setView(k)} style={{border:"1px solid #d0d5dd",background:view===k?"#101827":"#fff",color:view===k?"#fff":"#344054",borderRadius:999,padding:"9px 14px",fontWeight:800}}>{l}</button>)}</div>
  {view==="explore"&&<div style={{display:"grid",gap:14}}><div style={{display:"flex",gap:10,flexWrap:"wrap"}}><select value={destination} onChange={e=>setDestination(e.target.value as typeof destination)} style={{border:"1px solid #d0d5dd",borderRadius:12,padding:10}}>{botswanaPlaces.map(x=><option key={x}>{x}</option>)}</select><select value={kind} onChange={e=>setKind(e.target.value as typeof kind)} style={{border:"1px solid #d0d5dd",borderRadius:12,padding:10}}>{tourismExperienceTypes.map(x=><option key={x}>{x}</option>)}</select></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(230px,1fr))",gap:12}}>{items.map(x=><article key={x.id} style={{background:"#fff",border:"1px solid #e5e7eb",borderRadius:20,padding:18}}><small style={{color:"#2563eb",fontWeight:800}}>{x.type} · {x.location}</small><h3>{x.name}</h3><p style={{color:"#667085"}}>{x.price}</p><button onClick={()=>setItems(c=>c.map(y=>y.id===x.id?{...y,saved:!y.saved}:y))} style={{border:"1px solid #d0d5dd",borderRadius:10,padding:"8px 11px",background:x.saved?"#eff6ff":"#fff",fontWeight:800}}>{x.saved?"✓ Saved":"Save trip"}</button></article>)}</div></div>}
  {view==="itinerary"&&<div style={{background:"#fff",border:"1px solid #e5e7eb",borderRadius:22,padding:20}}><h2 style={{marginTop:0}}>3-day Botswana itinerary</h2>{[["Day 1","Arrival in Maun · lodge check-in · sunset activity"],["Day 2","Okavango Delta mokoro & wildlife experience"],["Day 3","Local culture stop · transfer / onward travel"]].map(([d,a])=><div key={d} style={{padding:"13px 0",borderBottom:"1px solid #f0f2f5"}}><strong>{d}</strong><div style={{fontSize:13,color:"#667085",marginTop:3}}>{a}</div></div>)}</div>}
  {view==="booking"&&<div style={{background:"#fff",border:"1px solid #e5e7eb",borderRadius:22,padding:20}}><h2 style={{marginTop:0}}>Booking enquiry</h2><p style={{color:"#667085"}}>Traveller details, dates, party size, selected experience and special requirements can be routed to Gmail/Outlook and saved into the operator's own workspace.</p><button style={{border:0,borderRadius:12,padding:"12px 18px",background:"#2563eb",color:"#fff",fontWeight:850}}>Create enquiry</button></div>}
  {view==="operator"&&<div style={{background:"#fff",border:"1px solid #e5e7eb",borderRadius:22,padding:20}}><h2 style={{marginTop:0}}>Operator dashboard</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(160px,1fr))",gap:12}}>{[["New enquiries","18"],["Upcoming trips","9"],["Saved experiences",String(items.filter(x=>x.saved).length)],["Conversion","36%"]].map(([l,v])=><div key={l} style={{border:"1px solid #e5e7eb",borderRadius:16,padding:16}}><div style={{fontSize:12,color:"#667085"}}>{l}</div><strong style={{fontSize:24}}>{v}</strong></div>)}</div></div>}
 </section>;
}
