"use client";

import { useState } from "react";
import { botswanaPlaces, logisticsJobStates, logisticsJobTypes } from "@bokang/domain-data";

type Job={id:string;client:string;type:string;from:string;to:string;driver:string;state:string};
const starter:Job[]=[{id:"MT-601",client:"Kgetsi Furnishers",type:"Furniture move",from:"Gaborone",to:"Molepolole",driver:"K. Dube",state:"In transit"},{id:"MT-602",client:"Northside Pharmacy",type:"Local delivery",from:"Gaborone",to:"Tlokweng",driver:"L. Moagi",state:"Driver assigned"}];
export function MoveTrackShowcase(){
 const [jobs,setJobs]=useState(starter); const [client,setClient]=useState(""); const [type,setType]=useState<(typeof logisticsJobTypes)[number]>("Local delivery"); const [from,setFrom]=useState<(typeof botswanaPlaces)[number]>("Gaborone"); const [to,setTo]=useState<(typeof botswanaPlaces)[number]>("Tlokweng"); const [view,setView]=useState<"jobs"|"new"|"fleet"|"analytics">("jobs");
 function add(){if(!client.trim())return;setJobs(c=>[{id:`MT-${600+c.length+1}`,client:client.trim(),type,from,to,driver:"Unassigned",state:"Quote requested"},...c]);setClient("");setView("jobs");}
 return <section style={{marginTop:28,display:"grid",gap:18}}>
  <div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{([["jobs","Jobs"],["new","New job"],["fleet","Fleet"],["analytics","Analytics"]] as const).map(([k,l])=><button key={k} onClick={()=>setView(k)} style={{border:"1px solid #d0d5dd",background:view===k?"#101827":"#fff",color:view===k?"#fff":"#344054",borderRadius:999,padding:"9px 14px",fontWeight:800}}>{l}</button>)}</div>
  {view==="jobs"&&<div style={{background:"#fff",border:"1px solid #e5e7eb",borderRadius:22,overflow:"hidden"}}>{jobs.map(x=><div key={x.id} style={{padding:16,borderBottom:"1px solid #f0f2f5",display:"grid",gap:6}}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><strong>{x.client}</strong><div style={{fontSize:12,color:"#667085"}}>{x.id} · {x.type} · {x.from} → {x.to} · {x.driver}</div></div><select value={x.state} onChange={e=>setJobs(c=>c.map(y=>y.id===x.id?{...y,state:e.target.value}:y))} style={{border:"1px solid #d0d5dd",borderRadius:12,padding:"8px 10px"}}>{logisticsJobStates.map(s=><option key={s}>{s}</option>)}</select></div></div>)}</div>}
  {view==="new"&&<div style={{background:"#fff",border:"1px solid #e5e7eb",borderRadius:22,padding:20}}><h2 style={{marginTop:0}}>Create delivery / move</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(200px,1fr))",gap:14}}><label style={{display:"grid",gap:6,fontSize:12,fontWeight:800}}>Client<input value={client} onChange={e=>setClient(e.target.value)} style={{border:"1px solid #d0d5dd",borderRadius:12,padding:11}}/></label><label style={{display:"grid",gap:6,fontSize:12,fontWeight:800}}>Job type<select value={type} onChange={e=>setType(e.target.value as typeof type)} style={{border:"1px solid #d0d5dd",borderRadius:12,padding:11}}>{logisticsJobTypes.map(x=><option key={x}>{x}</option>)}</select></label><label style={{display:"grid",gap:6,fontSize:12,fontWeight:800}}>From<select value={from} onChange={e=>setFrom(e.target.value as typeof from)} style={{border:"1px solid #d0d5dd",borderRadius:12,padding:11}}>{botswanaPlaces.map(x=><option key={x}>{x}</option>)}</select></label><label style={{display:"grid",gap:6,fontSize:12,fontWeight:800}}>To<select value={to} onChange={e=>setTo(e.target.value as typeof to)} style={{border:"1px solid #d0d5dd",borderRadius:12,padding:11}}>{botswanaPlaces.map(x=><option key={x}>{x}</option>)}</select></label></div><button onClick={add} style={{marginTop:16,border:0,borderRadius:12,padding:"12px 18px",background:"#2563eb",color:"#fff",fontWeight:850}}>Create job</button></div>}
  {view==="fleet"&&<div style={{background:"#fff",border:"1px solid #e5e7eb",borderRadius:22,padding:20}}><h2 style={{marginTop:0}}>Fleet status</h2>{[["B 123 ABC","Toyota Hilux","Available"],["B 884 XYZ","Isuzu Truck","On job"],["B 619 KLM","Ford Transit","Maintenance due"]].map(([reg,vehicle,status])=><div key={reg} style={{padding:"12px 0",borderBottom:"1px solid #f0f2f5",display:"flex",justifyContent:"space-between",gap:12}}><div><strong>{reg}</strong><div style={{fontSize:12,color:"#667085"}}>{vehicle}</div></div><span style={{fontSize:12,fontWeight:800}}>{status}</span></div>)}</div>}
  {view==="analytics"&&<div style={{background:"#fff",border:"1px solid #e5e7eb",borderRadius:22,padding:20}}><h2 style={{marginTop:0}}>Logistics snapshot</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(160px,1fr))",gap:12}}>{[["Active jobs",String(jobs.length)],["On-time","93%"],["Fleet utilisation","74%"],["POD complete","88%"]].map(([l,v])=><div key={l} style={{border:"1px solid #e5e7eb",borderRadius:16,padding:16}}><div style={{fontSize:12,color:"#667085"}}>{l}</div><strong style={{fontSize:24}}>{v}</strong></div>)}</div></div>}
 </section>;
}
